### ISSUE TITLE
don't understand Facet syntax

### ISSUE THREAD

**Issue by DeLeneMirouze** [reddog-io/RedDog.Search#14]
could you please give some more explanation about the Facet() syntax

in particular facetParameters
thanks

**Comment by ToonDC** [comment]
Currently you have to construct the facet string yourself. Note hat you can specify multiple facets strings. 
For example I have an index *People* with the fields *city* and *centimeters*. I want a facet by city but only the top 3, also I want to view the count of persons in a length (centimeters) range per 10 cm. The code to become this result can be implemented like this.

```c#
var apiConnection = ApiConnection.Create("name", "query-key");
            var queryClient = new IndexQueryClient(apiConnection);
            var result = await queryClient.SearchAsync("people", new SearchQuery()
                   .Facet("city", "count:3")
                   .Facet("centimeters", "values:140|150|160|170|180|190")); 
```
